### ISSUE TITLE
开启ssl功能，客户端报错

### ISSUE THREAD

**Issue by sunnerdu** [ffay/lanproxy#107]
2019-05-07 17:42:05,388 WARN [io.netty.channel.ChannelInitializer] - <Failed to initialize a channel. Closing: [id: 0x050c0382]>
java.lang.NullPointerException
        at org.fengfei.lanproxy.client.ProxyClientContainer.createSslHandler(ProxyClientContainer.java:99)
        at org.fengfei.lanproxy.client.ProxyClientContainer.access$2(ProxyClientContainer.java:98)
        at org.fengfei.lanproxy.client.ProxyClientContainer$2.initChannel(ProxyClientContainer.java:83)
        at org.fengfei.lanproxy.client.ProxyClientContainer$2.initChannel(ProxyClientContainer.java:1)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:118)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:104)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:846)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:453)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:370)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:420)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:748)
2019-05-07 17:42:05,394 WARN [org.fengfei.lanproxy.client.ProxyClientContainer] - <connect proxy server failed>
java.nio.channels.ClosedChannelException
2019-05-07 17:42:05,385 ERROR [org.fengfei.lanproxy.client.SslContextCreator] - <Unable to initialize SSL context. Cause = java.security.UnrecoverableKeyException: Password verification failed, errorMessage = Keystore was tampered with, or password was incorrect.>
2019-05-07 17:42:05,388 WARN [io.netty.channel.ChannelInitializer] - <Failed to initialize a channel. Closing: [id: 0x050c0382]>
java.lang.NullPointerException
        at org.fengfei.lanproxy.client.ProxyClientContainer.createSslHandler(ProxyClientContainer.java:99)
        at org.fengfei.lanproxy.client.ProxyClientContainer.access$2(ProxyClientContainer.java:98)
        at org.fengfei.lanproxy.client.ProxyClientContainer$2.initChannel(ProxyClientContainer.java:83)
        at org.fengfei.lanproxy.client.ProxyClientContainer$2.initChannel(ProxyClientContainer.java:1)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:118)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:104)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:846)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:453)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:370)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:420)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:748)
2019-05-07 17:42:05,394 WARN [org.fengfei.lanproxy.client.ProxyClientContainer] - <connect proxy server failed>
java.nio.channels.ClosedChannelException

**Comment by sadlay** [comment]
我也是
