### ISSUE TITLE
   配置信息 都存在哪？？？我想问问

### ISSUE THREAD

**Issue by xiaopeng1995** [ffay/lanproxy#38]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.fengfei.lanproxy.server.ProxyServerContainer.<init>(ProxyServerContainer.java:61)
	at org.fengfei.lanproxy.server.ProxyServerContainer.main(ProxyServerContainer.java:174)
Caused by: java.lang.IllegalArgumentException: 一个公网端口只能映射一个后端信息，不能重复: 81‘

总是出现这个问题  我用了一台新linux服务器  81没有占有   一打开 就是这个问题 不能重复81    
我81 端口没有用过呀  不知道怎么解决 启动不了！！！！！！   配置信息 都存在哪？？？我想问问

**Comment by ffay** [comment]
~/.lanproxy/ 目录中存放的配置文件，删除后再试试

**Comment by xiaopeng1995** [comment]
找不到

**Comment by xiaopeng1995** [comment]
找到了
